title: 16th Annual Biocuration Conference
name: International Society of Biocuration
description: April 25th-28th, 2023 in Padova, Italy at the Cultural Center Altinate San Gaetano

theme: minima
github_username: biocuration
twitter_username: biocurator

plugins:
  - jekyll-feed
  - jekyll-sitemap
